version: '3.7'
services:
    web: 
        build: ../Dockerfile
        ports:
            - "5000:3000"
        volumes:
            - .:/app
        depends_on:
            - db
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=manage_graduation_se_iuh
        ports:  
            - "3306:3306"

