version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: manage_graduation_se_iuh
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-network

  api-server:
    build:
      context: .
    container_name: api-server
    ports:
      - "3000:3000"
    networks:
      - app-network
    
  client-student:
    build:
      context: ../client-student
    container_name: client-student
    ports:
      - "5174:80"
    networks:
      - app-network

  client-lecturer:
    build:
      context: ../client-lecturer
    container_name: client-lecturer
    ports:
      - "5173:80"
    networks:
      - app-network

  chatbot:
    build:
      context: ./chatbot
    container_name: chatbot
    ports:
      - "8000:8000"
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
  
networks:
  app-network:
    driver: bridge